# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
#  use_frameworks!

target 'IoT-Electronics-mobileApp-SWIFT' do
pod 'IMFCore'
pod 'MQTTClient', ‘0.4.0’
end